/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/calls`; params?: Router.UnknownInputParams; } | { pathname: `/chatList`; params?: Router.UnknownInputParams; } | { pathname: `/chatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/newChat`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/DefaultAvatar`; params?: Router.UnknownInputParams; } | { pathname: `/components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/components/Modal`; params?: Router.UnknownInputParams; } | { pathname: `/components/VoiceNoteBubble`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/calls`; params?: Router.UnknownOutputParams; } | { pathname: `/chatList`; params?: Router.UnknownOutputParams; } | { pathname: `/chatScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/layout`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/main`; params?: Router.UnknownOutputParams; } | { pathname: `/newChat`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/components/DefaultAvatar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Input`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Modal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/VoiceNoteBubble`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/calls${`?${string}` | `#${string}` | ''}` | `/chatList${`?${string}` | `#${string}` | ''}` | `/chatScreen${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/layout${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `/newChat${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/Button${`?${string}` | `#${string}` | ''}` | `/components/DefaultAvatar${`?${string}` | `#${string}` | ''}` | `/components/Input${`?${string}` | `#${string}` | ''}` | `/components/Modal${`?${string}` | `#${string}` | ''}` | `/components/VoiceNoteBubble${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/calls`; params?: Router.UnknownInputParams; } | { pathname: `/chatList`; params?: Router.UnknownInputParams; } | { pathname: `/chatScreen`; params?: Router.UnknownInputParams; } | { pathname: `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/layout`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/newChat`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/components/DefaultAvatar`; params?: Router.UnknownInputParams; } | { pathname: `/components/Input`; params?: Router.UnknownInputParams; } | { pathname: `/components/Modal`; params?: Router.UnknownInputParams; } | { pathname: `/components/VoiceNoteBubble`; params?: Router.UnknownInputParams; };
    }
  }
}
